# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-29 15:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show', '0005_hostfiles'),
    ]

    operations = [
        migrations.CreateModel(
            name='NetworkID',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('network_ID', models.CharField(max_length=15)),
                ('hostname', models.CharField(max_length=200)),
                ('interface_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='hostfiles',
            name='lines',
            field=models.FilePathField(path=b'/etc/ansible/showsite/host_path'),
        ),
        migrations.AlterField(
            model_name='textfiles',
            name='lines',
            field=models.FilePathField(path=b'/etc/ansible/showsite/textfiles'),
        ),
    ]
