# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-29 15:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show', '0006_auto_20160729_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostfiles',
            name='lines',
            field=models.FilePathField(path=b'/etc/ansible/showsite/hostlists'),
        ),
    ]
