# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-02 17:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show', '0008_networkid_mask'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutomaticGen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily', models.BooleanField(default=False)),
                ('hour', models.PositiveIntegerField()),
                ('minute', models.PositiveIntegerField()),
            ],
        ),
    ]
