# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-11 14:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show', '0009_automaticgen'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=200)),
                ('date', models.CharField(max_length=200)),
                ('connected', models.IntegerField()),
                ('notconnected', models.IntegerField()),
            ],
        ),
    ]
